/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    // App dependencies.
    implementation("org.apache.beam:beam-sdks-java-core:2.59.0")
    implementation("org.apache.beam:beam-runners-direct-java:2.59.0")
    implementation("org.apache.beam:beam-sdks-java-io-solace:2.59.0")
    implementation("org.apache.beam:beam-sdks-java-io-jms:2.59.0")
    implementation("org.apache.qpid:qpid-jms-client:0.47.0")
    implementation("org.slf4j:slf4j-jdk14:1.7.32")
    implementation("org.json:json:20240303")

    // Tests dependencies.
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.hamcrest:hamcrest:2.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.register("hello") {
    doLast{
        println("Hello!")
    }
}

tasks.register("greet") {
    doLast {
        println("How are you?")
    }
    dependsOn("hello")
}